### PR TITLE
Enable cold folding in editor

### PR DESCRIPTION
**Pull request by dekpient**
Hi,

First off, thanks for making and open-sourcing this extension. I really like the simplicity of this extension.

The problem is my user script is getting quite big, so cold folding makes viewing the script easier for me. The add-on scripts are from CodeMirror master branch as I couldn't find the version you're using. I built and tested on my machine, it's working fine so far. 

Let me know if I need to fix anything.
Cheers!

### CODE REVIEW

**Comment by quoid** [comment]
Thanks @dekpient, I am going to test locally and if it all is well, I will push v1.5.0 with this feature. I appreciate the efforts.

**Comment by quoid** [comment]
@dekpient 

It looks and seems to work well. I pushed the code to the v1.5.0, with minor edits from me.

If all continues to work well, I will push the new version early next week and update the app store version.

**Comment by dekpient** [comment]
@quoid Awesome, thanks!

**Comment by quoid** [comment]
@dekpient - [v1.5.0](https://github.com/quoid/userscripts/releases/tag/v1.5.0) has been merged into master and a release has been created.

I've submitted it to the Mac App Store and should be pushed to users after approved; thanks again.

**Pull request merged**
